### ISSUE TITLE
Support .aspx pages in urls

### ISSUE THREAD

**Issue by Korayem** [cowboy/javascript-linkify#1]
Please support .aspx pages in urls

**Comment by cowboy** [comment]
I don't understand your request, [http://example.com/file.aspx](http://benalman.com/code/projects/javascript-linkify/examples/linkify/?x=http%3A%2F%2Fexample.com%2Ffile.aspx) linkifies just fine. Can you link to an example that doesn't work?

**Comment by Korayem** [comment]
I tried a link on my website and it didn't work. May be it was my bad. Never mind.

Thanks
